#!/bin/bash
#read -p 'input name of the server: ' srv_name #работает

fin_cd_exec_func(){

#for i in $(find /home/dedicadmin/parsers_reg_*/pd_ -maxdepth 1 -type d -name "mgk_*_pd_all*")

#for i in $(find /home/dedicadmin/parsers_reg_*/pd_ -maxdepth 1 -type d -name "dmr_*" -o -name "mgk_*_pd_all*" -o -name "len_app_*" -o -name "podruzhka_app_*" -o -name "ash_*" -o -name "dx_app_*" -o -name "glb_*" -o -name "gldappl_app_*" -o -name "magnit_dostavka_app_*" -o -name "per_*" -o -name "sel_app_*" -o -name "sm_alleya_*" -o -name "sm_bet_*" -o -name "sm_mgt_*" -o -name "spar_web_*" -o -name "tvd_web_*" -o -name "ulr_*")  

for i in $(find /home/dedicadmin/parsers_reg_*/pd_ -maxdepth 1 -type d -name "dmr_*")

do (
  #cd $(dirname $(realpath $i));
  cd -- $i 
     git pull

  if [ -n "$(ls | grep Pipfile.dist)" ]
  then
  pwd
  #ls | grep Pipfile.dist 
    
   
    #mv -f Pipfile Pipfile_auto.bak
    #mv -f Pipfile.lock Pipfile_auto.lock.bak
    #cp -rp Pipfile.dist Pipfile
    pipenv install

    #pipenv run bash run.sh
  
  else
  echo "there is no file named Pipfile.dist in the folder: $i "
  fi
)
done
}
#fin_cd_exec_func "$srv_name"
fin_cd_exec_func


#ручные сети (нужно залить)
#/home/dedicadmin/parsers_reg_012/ok_spl-fmcg/lenta_price_parser_scr_0022 == (она не в пд)
#/home/dedicadmin/parsers_reg_012/pd_/dmr_220_mc_sp == ++dmr_*++
#/home/dedicadmin/parsers_reg_012/pd_/len_app_0161_pd_all == ++len_app_*++
#/home/dedicadmin/parsers_reg_012/pd_/podruzhka_app_13671_pd_all_2 == ++podruzhka_app_*++

#сети у которых уже есть пипфайл, с 12 серва

#/home/dedicadmin/parsers_reg_012/pd_/mgk_104865_pd_all == ++mgk_*_pd_all*++ 
#/home/dedicadmin/parsers_reg_012/pd_/ash_35_pd_all == ++ash_*++
#/home/dedicadmin/parsers_reg_012/pd_/dx_app_77227_mc_sp == ++dx_app_*++
#/home/dedicadmin/parsers_reg_012/pd_/glb_5014_mc_sp_2 == ++glb_*++
#/home/dedicadmin/parsers_reg_012/pd_/gldappl_app_spb_pd_all_1 == ++gldappl_app_*++
#/home/dedicadmin/parsers_reg_012/pd_/magnit_dostavka_app_330077_pd_all == ++magnit_dostavka_app_*++
##/home/dedicadmin/parsers_reg_012/pd_/per_1061_pd_all == ++per_*++
#/home/dedicadmin/parsers_reg_012/pd_/sel_app_591_pd_all_3 == ++sel_app_*++
#/home/dedicadmin/parsers_reg_012/pd_/sm_alleya_462_pd_all/out #при созд шаблона нужно одно от другого отделить (возможно) == ++sm_alleya_*+
#/home/dedicadmin/parsers_reg_012/pd_/sm_alleya_462_pd_all_alco == такой же
#/home/dedicadmin/parsers_reg_012/pd_/sm_bet_669_pd_all == ++sm_bet_*++
#/home/dedicadmin/parsers_reg_012/pd_/sm_mgt_2168_pd_all == ++sm_mgt_*++
#/home/dedicadmin/parsers_reg_012/pd_/spar_web_782_pd_all_1 == ++spar_web_*++
#/home/dedicadmin/parsers_reg_012/pd_/tvd_web_20_pd_fmcg_3 == ++tvd_web_*++
#/home/dedicadmin/parsers_reg_012/pd_/ulr_163493_mc_sp_5 == ++ulr_*++
