#!/bin/bash

function for_loop { 
	for f in $(find /home/myadmin/parsers_reg_* -maxdepth 2 -type d | awk '$1 ~ /zvr_/ && $1 !~ /vl/ {print $0}')
	do
        if [ -d $f  -a ! -h $f ]  
        then  
            cd -- "$f"  
			if [ "$(ls | grep Pipfile.dist)" = "Pipfile.dist" ]
			then
				
				pwd
			
			fi	
		fi  
	done 
}
for_loop
