#!/bin/bash
#---Блок получения рандомной категории
  #авк обрезает выход от вс -л - он содержит полезную информацию только в $1
count_str_in_file=$(wc -l test_categories.csv | awk '{print $1}')
#echo count_str_in_file: $count_str_in_file

randome="$(( $RANDOM % $count_str_in_file + 1 ))"
categ_id=$(cat test_categories.csv | awk 'BEGIN{FS=";"}{print $2}' | sed -n "$randome p" | tr -d '\r')
echo categ_id: $categ_id

  #Запись рандомной категории в джсон

jq --argjson d ${categ_id} '.shops[0].categories[0] = $d' config.json > "tmp" && mv "tmp" config.json



#---Блок получения и записи тт_ид
user_input_tt_id=$1
if [ -n "$user_input_tt_id" ]
  then
    echo user_input_tt_id: $user_input_tt_id

    #Блок записи тт_ид (если введена)
    jq --argjson d "${user_input_tt_id}" '.shops[0].ids[0] = $d' config.json > "tmp" && mv "tmp" config.json

  else
    echo "user_input_tt_id: none"

fi


#---Блок работы с координатами
if [ -n "$user_input_tt_id" ]
  then
    lat_coord=$(cat shops.csv | awk 'BEGIN{FS=";"}{
    if ($1 ~ var_in_awk)
    {
    print $0
    }
    }' var_in_awk="${user_input_tt_id}" | awk 'BEGIN{FS=";"}{print $5}' | tr -d '\r')

    lon_coord=$(cat shops.csv | awk 'BEGIN{FS=";"}{
    if ($1 ~ var_in_awk)
    {
    print $0
    }
    }' var_in_awk="${user_input_tt_id}" | awk 'BEGIN{FS=";"}{print $6}' | tr -d '\r')

    addr_in_csv=$(cat shops.csv | awk 'BEGIN{FS=";"}{
    if ($1 ~ var_in_awk)
    {
    print $0
    }
    }' var_in_awk="${user_input_tt_id}" | awk 'BEGIN{FS=";"}{print $4}' | tr -d '\r' | tr -d '"')

  echo lat_coord: $lat_coord lon_coord: $lon_coord addr_in_csv: $addr_in_csv

	#запись полученных координат в джсон и адреса

  jq --argjson k "${lat_coord}" '.shops[0].lat = $k' config.json > "tmp" && mv "tmp" config.json
  jq --argjson k "${lon_coord}" '.shops[0].lng = $k' config.json > "tmp" && mv "tmp" config.json
  jq --arg k "${addr_in_csv}" '.shops[0].address = $k' config.json > "tmp" && mv "tmp" config.json

fi



#---Блок запуска
sleep 2s
#pipenv run bash run.sh 



