#!/bin/bash
#---Блок получения рандомной категории
  #Считает количество строк в файле. авк обрезает выход от вс -л - он содержит полезную информацию только в $1
count_str_in_file=$(wc -l test_categories.csv | awk '{print $1}')
  #echo count_str_in_file: $count_str_in_file

randome="$(( $RANDOM % $count_str_in_file + 1 ))"
categ_id=$(cat test_categories.csv | awk 'BEGIN{FS=";"}{print $2}' | sed -n "$randome p" | tr -d '\r')
echo categ_id: $categ_id

  #Запись рандомной категории в джсон

#jq --arg d ${categ_id} '.shops[0].categories[0] = $d' config.json > "tmp" && mv "tmp" config.json



#---Блок получения и записи тт_ид
user_input_tt_id=$1
if [ -n "$user_input_tt_id" ]
  then
    echo user_input_tt_id: $user_input_tt_id

    #Блок записи тт_ид (если введена)
    #jq --arg d "${user_input_tt_id}" '.shops[0].id = $d' config.json > "tmp" && mv "tmp" config.json

  else
    echo "user_input_tt_id: none"

fi


#---Блок получения и записи региона - ищет строку по введённому человеком тт_ид, из строки вынимает регион_ид, удаляет символ возврата коретки; так же вынимает имя региона. Если не введён тт_ид, не отрабатывает
if [ -n "$user_input_tt_id" ]
  then
  
  #блок получения номера строки, содержащий тт_ид - тт_ид встречается в координатах, потом греп может давать много строк. Логика фильтрует строки по 2-му столбцу, 
  #выводит все строки файла в "виде ттид_номерстроки" - в этом выводе присутствует нижнее подчёркивание, далее греп ищет по тт_ид в начале и _ нижнему подчёрккиванию вконце (чтобы отфильтровать входления коротких тт ид в другие номера, например 262)
  #Далее из вывода записывается только номер строки в переменную стр_нум
	

  str_num=$(cat shops.csv | awk 'BEGIN{FS=";"; OFS="_"}{print $2,FNR}' | grep -E "^${user_input_tt_id}_" | awk 'BEGIN{FS="_"}{print $2}')
  #echo str_num $str_num

  #Блок получения рег_ид из строки с номером str_num
  
  if [ -n "$str_num" ] 
  then

    reg_id=$(cat shops.csv | sed -n "$str_num p" | awk 'BEGIN{FS=";"}{print $8}' | tr -d '\r')
    echo reg_id: $reg_id

  else
    echo "!!! тт_ид не найден в файле шопс; регион_ид не получен"
    flag="none"

  fi

fi
 

#---Блок записи рег_ид в конфиг; регнэйм при этом не пишется, а просто выводится на экран для простоты дебага
jq --arg d "${reg_id}" '.shops[0].region_id = $d' config.json > "tmp" && mv "tmp" config.json


#---Блок запуска
if [ "$flag" = "none" ]
then

  echo "Парсер не запущен" 

else
  sleep 2s
  #pipenv run bash run.sh 

fi


